name: Build and deploy to Azure Web App - thoughts-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thoughts-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3304427f5e0f4c3e8931ef9cb3196ae2 }}
        package: ${{env.DOTNET_ROOT}}/myapp 